---
title: "About the Paycheck Protection Program Data Website"
description: |
  Lots of data made more easily available than huge raw tables.
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

I found it quite difficult to parse the large files provided by the SBA that contained who got what in regards to the PayCheck Protection Program. So, I merged and cleaned the files and then but them into a database so that others could find them more easily. 

Other sites have done similar things, notably, ProPublica [has an excellent site of PPP data](https://projects.propublica.org/coronavirus/bailouts/). However, we add some value:

1. The data here is newer (by about 5 months) 
2. It includes exact amounts (instead of ranges). 
3. We *may* include more data. The raw data includes loans under $150k, unlike other sources. However, as is, a lack of computer processing power makes it so that this website only serves up a fraction of the records that have the highest loan amounts. When I have more time (and can pay for time on a multi-core supercomputer) I'll add more records.

Note that currently the search functionality is limited. But I'm working to make it better.

So ProPublica is great, and may be more comprehensive. So check them out!