---
title: "Paycheck Protection Program - Summary Statistics"
description: |
  Data and statistics about the Paycheck Protection Program. 
author:
  - name: Paycheck Protection Program Data
date: 12-09-2020
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(formattable)
library(kableExtra)
library(data.table)
# library(dtplyr)
library(dplyr, warn.conflicts = FALSE)
library(feather)
library(DT)
library(highcharter)
library(magrittr)


db <- read_feather("../ppp builder-PRIVATE/inter/ppp.all.feather")

# db <- lazy_dt(db)


```


## All PPP Loans (as of Nov. 2020)

```{r db.summary}

db.summary <- db %>%
  summarize(
    `Number of Loans` = prettyNum(n(),big.mark=","),
    `Total Amount Loaned` = currency(sum(LoanAmount), digits = 0L),
    `Average Loan` = currency(mean(LoanAmount), digits = 0L),
    `Dollars per Job Reported` = currency(sum(LoanAmount) / sum(JobsReported, na.rm =
                                                                  TRUE), digits = 0L)
  )

knitr::kable(t(db.summary), 
col.names = '') %>%
kable_styling(latex_options = 'striped') %>%
  column_spec(1, bold = TRUE)

```

<br>
<br>
<br>

## Loans by State


```{r db.state.summaries}

db.state.summaries <- db %>%
  group_by(State) %>%
  summarize(
    `Number of Loans` = prettyNum(n(),big.mark=","),
    `Total Amount Loaned` = sum(LoanAmount, na.rm = TRUE),
    `Average Loan` =mean(LoanAmount), 
    `Dollars per Job Reported` =sum(LoanAmount) / sum(JobsReported, na.rm =
                                                                  TRUE)
  ) %>%
  filter(!State %in% c("AE", "Missing State", "FI")) %>%
  arrange(desc(`Total Amount Loaned`))

numcols <- dplyr::select_if(db.state.summaries, is.numeric) %>%
  colnames()

db.state.summaries %<>% mutate(across(where(is.numeric), round, 0))



DT::datatable(db.state.summaries) %>%
  formatRound(columns= numcols, digits=0)

```

<br>
<br>
<br>

## DC had the Highest Average loan (but caution, DC is a city, where others are states with rural areas)

```{r}

hcoptslang <- getOption("highcharter.lang")
hcoptslang$thousandsSep <- ","
options(highcharter.lang = hcoptslang)

hc <- db.state.summaries %>%
  arrange(desc(`Average Loan`)) %>%
  hchart(
  'bar', hcaes(x = State, y = `Average Loan`),
  name = "Average Loan"
  )

hc


```

